apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogcomment-api-deployment
  labels:
    app: blogcomment-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogcomment-api
  template:
    metadata:
      labels:
        app: blogcomment-api
    spec:
      containers:
      - name: blogcomment-api
        image: rimbik/techlabs-pub:v1.0.bc
        ports:
        - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: blogcomment-api-service
spec:
  type: NodePort
  selector:
    app: blogcomment-api
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002      
      nodePort: 30002  