version: '3.4'

services:
  blogpost-api:
    image: ${DOCKER_REGISTRY-}img-blogpostapi:v1.0
    build:
      context: .
      dockerfile: blogpost-api/Dockerfile
  
  blogcomment-api:
    image: ${DOCKER_REGISTRY-}img-blogcommentapi:v1.0
    build:
      context: .
      dockerfile: blogcomment-api/Dockerfile
  
  queryms-api:
    image: ${DOCKER_REGISTRY-}img-querymsapi:v1.0
    build:
      context: .
      dockerfile: queryms-api/Dockerfile

  eventbus-api:
    image: ${DOCKER_REGISTRY-}img-eventbusapi:v1.0
    build:
      context: .
      dockerfile: eventbus-api/Dockerfile