version: '3.4'

services:
  blogpost-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      #- "4001" fix url to browse port fwd (http://localhost:4001/swagger/index.html)
      - "4001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  blogcomment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  queryms-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  eventbus-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      #- "4005" fix url to browse port fwd (http://localhost:4005/swagger/index.html)
      - "4005:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro