apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-api-deployment
  labels:
    app: eventbus-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventbus-api
  template:
    metadata:
      labels:
        app: eventbus-api
    spec:
      containers:
      - name: cont-eventbus-api
        image: rimbik/techlabs-pub:v1.0.eb
        ports:
        - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-api-service
spec:
  type: NodePort
  selector:
    app: eventbus-api
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005      
      nodePort: 30005  