apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpost-api-deployment
  labels:
    app: blogpost-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogpost-api
  template:
    metadata:
      labels:
        app: blogpost-api
    spec:
      containers:
      - name: blogpost-api
        image: rimbik/techlabms:v1.0.bp
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: blogpost-api-service
spec:
  type: NodePort
  selector:
    app: blogpost-api
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001      
      nodePort: 30001  