apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-api-deployment
  labels:
    app: eventbus-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventbus-api
  template:
    metadata:
      labels:
        app: eventbus-api
    spec:
      containers:
      - name: cont-eventbus-api
        image: img-eventbusapi
        ports:
        - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-api.service
spec:
  selector:
    app: eventbus-api
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005